# Generated by Django 4.2.6 on 2023-10-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtaurora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
