# Generated by Django 4.2.6 on 2023-10-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtaurora', '0003_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(blank=True, max_length=255)),
                ('owner_phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('needed_repairs', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='volunteer',
            name='availability',
            field=models.CharField(choices=[('asneeded', 'As Needed'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], default='asneeded', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='dob',
            field=models.DateField(default='2023-10-07'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='isAdult',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='preference',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='reference',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='role',
            field=models.CharField(choices=[('general', 'General Volunteer'), ('carpentry', 'Carpentry'), ('window', 'Window replacement'), ('drywall', 'Drywall/Plaster work'), ('flooring', 'Flooring'), ('painting', 'Painting'), ('hvac', 'HVAC'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('landscaping', 'Landscaping')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='shirt',
            field=models.CharField(choices=[('xsmall', 'XSmall'), ('small', 'small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'XLarge'), ('2xlarge', '2XLarge'), ('3xlarge', '3XLarge')], default='small', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='state',
            field=models.CharField(choices=[('na', 'Choose State'), ('OH', 'Ohio'), ('MI', 'Michigan')], default='na', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='street',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='zipCode',
            field=models.IntegerField(default=0),
        ),
    ]
