# Generated by Django 4.2.6 on 2023-10-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtaurora', '0004_house_volunteer_availability_volunteer_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminUsername', models.CharField(max_length=255, unique=True)),
                ('adminPassword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='volunteerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteerUsername', models.CharField(max_length=255, unique=True)),
                ('volunteerPassword', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='shirt',
            field=models.CharField(choices=[('xsmall', 'XSmall'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'XLarge'), ('2xlarge', '2XLarge'), ('3xlarge', '3XLarge')], default='small', max_length=20),
        ),
    ]
