# Generated by Django 4.2.6 on 2023-10-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtaurora', '0004_house_volunteer_availability_volunteer_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('na', 'Choose Rating'), ('1', 'Very Negative'), ('2', 'Negative'), ('3', 'Neutral'), ('4', 'Positive'), ('5', 'Very Positive')], default='na', max_length=2)),
                ('text', models.TextField(default='')),
                ('house', models.CharField(default='', max_length=255)),
                ('volunteer_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='house_id',
            field=models.CharField(default=15, max_length=6),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='shirt',
            field=models.CharField(choices=[('xsmall', 'XSmall'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'XLarge'), ('2xlarge', '2XLarge'), ('3xlarge', '3XLarge')], default='small', max_length=20),
        ),
    ]
