# Generated by Django 4.2.6 on 2023-10-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtaurora', '0004_house_volunteer_availability_volunteer_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='address',
            new_name='familyName',
        ),
        migrations.RemoveField(
            model_name='house',
            name='needed_repairs',
        ),
        migrations.RemoveField(
            model_name='house',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='house',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='house',
            name='owner_phone',
        ),
        migrations.AddField(
            model_name='house',
            name='application',
            field=models.FileField(blank=True, null=True, upload_to='../HouseApplication'),
        ),
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='familyEmail',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='recievedOn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='state',
            field=models.CharField(choices=[('na', 'Choose State'), ('OH', 'Ohio'), ('MI', 'Michigan')], default='na', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='zipCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='shirt',
            field=models.CharField(choices=[('xsmall', 'XSmall'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'XLarge'), ('2xlarge', '2XLarge'), ('3xlarge', '3XLarge')], default='small', max_length=20),
        ),
    ]
