# Generated by Django 4.2.6 on 2023-10-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtaurora', '0005_adminuser_volunteeruser_delete_house_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('na', 'Choose Rating'), ('1', 'Very Negative'), ('2', 'Negative'), ('3', 'Neutral'), ('4', 'Positive'), ('5', 'Very Positive')], default='na', max_length=2)),
                ('text', models.TextField(default='')),
                ('house', models.CharField(default='', max_length=255)),
                ('volunteer_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.CharField(default=13, max_length=6)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(blank=True, max_length=255)),
                ('owner_phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('needed_repairs', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='volunteer',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
