# Generated by Django 4.2.6 on 2023-10-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.IntegerField(default=0)),
                ('preference', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=20)),
                ('street', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('na', 'Choose State'), ('OH', 'Ohio'), ('MI', 'Michigan'), ('IL', 'Illinois')], default='na', max_length=255)),
                ('city', models.TextField(blank=True)),
                ('zipCode', models.IntegerField(default=0)),
                ('dob', models.DateField(default='2023-10-07')),
                ('isAdult', models.BooleanField(default=True)),
                ('shirt', models.CharField(choices=[('xsmall', 'XSmall'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'XLarge'), ('2xlarge', '2XLarge'), ('3xlarge', '3XLarge')], default='small', max_length=20)),
                ('availability', models.CharField(choices=[('asneeded', 'As Needed'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], default='asneeded', max_length=20)),
                ('role', models.CharField(choices=[('general', 'General Volunteer'), ('carpentry', 'Carpentry'), ('window', 'Window replacement'), ('drywall', 'Drywall/Plaster work'), ('flooring', 'Flooring'), ('painting', 'Painting'), ('hvac', 'HVAC'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('landscaping', 'Landscaping')], default='general', max_length=20)),
                ('other', models.TextField(blank=True)),
                ('reference', models.TextField(blank=True)),
                ('hours', models.IntegerField(default=0)),
            ],
        ),
    ]
