# Generated by Django 4.2.6 on 2023-10-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtaurora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminUsername', models.CharField(max_length=255, unique=True)),
                ('adminPassword', models.CharField(max_length=255)),
            ],
        ),
    ]
