# Generated by Django 4.2.6 on 2023-10-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtaurora', '0002_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteerUsername', models.CharField(max_length=255, unique=True)),
                ('volunteerPassword', models.CharField(max_length=255)),
            ],
        ),
    ]
