# Generated by Django 4.2.6 on 2023-10-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtaurora', '0003_volunteeruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyName', models.CharField(max_length=255)),
                ('familyEmail', models.EmailField(blank=True, max_length=255, null=True)),
                ('familyDescription', models.TextField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('na', 'Choose State'), ('OH', 'Ohio'), ('MI', 'Michigan'), ('IL', 'Illinois')], default='na', max_length=2, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('zipCode', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('recievedOn', models.DateField(blank=True, null=True)),
                ('application', models.FileField(blank=True, null=True, upload_to='HouseApplications')),
                ('houseImage', models.ImageField(blank=True, null=True, upload_to='HouseImages')),
            ],
        ),
    ]
