# Generated by Django 4.2.6 on 2023-10-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtaurora', '0004_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street', models.TextField()),
                ('state', models.CharField(choices=[('na', 'Choose State'), ('OH', 'Ohio'), ('MI', 'Michigan'), ('IL', 'Illinois')], default='na', max_length=2)),
                ('city', models.TextField()),
                ('zipCode', models.IntegerField()),
                ('mainContact', models.CharField(max_length=255)),
                ('mainEmail', models.EmailField(blank=True, max_length=255)),
            ],
        ),
    ]
