# Generated by Django 4.2.6 on 2023-10-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtaurora', '0005_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('na', 'Choose Rating'), ('1', 'Very Negative'), ('2', 'Negative'), ('3', 'Neutral'), ('4', 'Positive'), ('5', 'Very Positive')], default='na', max_length=2)),
                ('text', models.TextField(default='')),
                ('house', models.CharField(default='', max_length=255)),
                ('volunteer_name', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
