# Generated by Django 4.2.3 on 2023-10-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtaurora', '0006_feedbackform'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeruser',
            name='volunteerID',
            field=models.CharField(default='', max_length=255),
        ),
    ]
